[scrapyd]
bind_address = 0.0.0.0
http_port = 6800
maxproc = 2
logs_dir = /var/lib/scrapyd/logs
items_dir = /var/lib/scrapyd/items
jobs_dir = /var/lib/scrapyd/jobs
dbs_dir = /var/lib/scrapyd/dbs
eggs_dir = /var/lib/scrapyd/eggs