apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealwallet-scheduler
spec:
  replicas: 1

  selector:
    matchLabels:
      app: dealwallet-scheduler

  template:
    metadata:
      labels:
        app: dealwallet-scheduler

    spec:
      containers:
        - name: dealwallet-scheduler
          image: ghcr.io/dealwallet1/dealwallet-scrapy:e756fc3
          imagePullPolicy: Always

          command:
            - python

          args:
            - scheduler.py

          envFrom:
            - secretRef:
                name: dealwallet-scrapy-secret

          env:
            - name: TZ
              value: Asia/Kolkata

            - name: SCRAPYD_URL
              value: "http://dealwallet-scrapyd:4079"

            - name: SCRAPYD_PROJECT
              value: "dealwallet_scraper"

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "1Gi"