apiVersion: v1
kind: Secret

metadata:
  name: dealwallet-scrapy-secret

type: Opaque

stringData:
  DB_HOST: "db.chatbot-backend.dealwallet.com"
  DB_PORT: "30445"
  DB_NAME: "chatbot_backend_db"
  DB_USER: "chatbot_backend_user"
  DB_PASSWORD: "tsss@2026@chatbot"

  SCRAPYD_URL: "http://dealwallet-scrapyd:6800/schedule.json"
  SCRAPYD_PROJECT: "dealwallet_scraper"
  SCHEDULE_INTERVAL_SECONDS: "6000"
  LOG_LEVEL: "INFO"
