apiVersion: v1
kind: Service

metadata:
  name: dealwallet-scrapyd

spec:
  type: LoadBalancer

  selector:
    app: dealwallet-scrapyd

  ports:
    - name: http
      port: 6800
      targetPort: 6800
      protocol: TCP